name: buildfork

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4.2.2
        with:
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm tests -- --coverage
        env:
          CI:  true
      - name: Upload code coverage
        uses: actions/upload-artifact@4.6.1
        with:
          name: codecoverage
          path: codecoverage
      - name: build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: build
          path: build
